Add XML documentation to ResourceGroupOperations.cs
m-nash/azure-proto-sdk pull request #104
Opened 2021-01-09 00:11 UTC by nisha-bhatia

2021-01-09 00:12 UTC, nisha-bhatia commented
ADO item: https://dev.azure.com/azure-mgmt-ex/DotNET%20Management%20SDK/_boards/board/t/DotNET%20Management%20SDK%20Team/Stories/?workitem=5056

2021-01-09 00:22 UTC, m-nash requested changes

2021-01-09 00:22 UTC, m-nash commented on Azure.ResourceManager.Core/ResourceGroupOperations.cs
> +        /// Gets initializes a new instance of the <see cref="ResourceType"/> class.
remove gets and change to ResourceGroupOperations type
```suggestion
        /// Initializes a new instance of the <see cref="ResourceGroupOperations"/> class.
```

2021-01-09 00:22 UTC, m-nash commented on Azure.ResourceManager.Core/ResourceGroupOperations.cs
> +        /// Deletes a ResourceGroupOperations.
Pull this text from the actual RP operations class
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/resources/Azure.ResourceManager.Resources/src/Generated/ResourceGroupsOperations.cs#L291

2021-01-09 00:22 UTC, m-nash commented on Azure.ResourceManager.Core/ResourceGroupOperations.cs
> +        /// <summary>
use inerhitdoc here since its an overriden method

/// <inheritdoc/>

2021-01-09 00:22 UTC, m-nash commented on Azure.ResourceManager.Core/ResourceGroupOperations.cs
> +        /// <summary>
use inerhitdoc here since its an overriden method

/// <inheritdoc/>

2021-01-09 00:22 UTC, m-nash commented on Azure.ResourceManager.Core/ResourceGroupOperations.cs
> +        /// <summary>
update to follow this
https://github.com/m-nash/azure-proto-sdk/blob/master/XmlDocStandard.md#tags

2021-01-11 18:30 UTC, m-nash requested changes

2021-01-11 18:30 UTC, m-nash commented on Azure.ResourceManager.Core/ResourceGroupOperations.cs
> +        /// Gets the resource type definition for a [Resource].
replace [Resource]

2021-01-11 18:30 UTC, m-nash commented on Azure.ResourceManager.Core/ResourceGroupOperations.cs
> +        /// <inheritdoc/>
the inherit doc replaces the entire /// summary

2021-01-11 18:30 UTC, m-nash commented on Azure.ResourceManager.Core/ResourceGroupOperations.cs
> +        /// <inheritdoc/>
the inherit doc replaces the entire /// summary

2021-01-11 21:33 UTC, closed without merging