Add XML Documentation to AzureSubscriptionExtension.cs
m-nash/azure-proto-sdk pull request #112
Opened 2021-01-12 01:37 UTC by nisha-bhatia

2021-01-12 01:38 UTC, nisha-bhatia commented
ADO item: https://dev.azure.com/azure-mgmt-ex/DotNET%20Management%20SDK/_boards/board/t/DotNET%20Management%20SDK%20Team/Stories/?workitem=4897

2021-01-12 19:51 UTC, m-nash requested changes

2021-01-12 19:51 UTC, m-nash commented on azure-proto-compute/Extensions/AzureSubscriptionExtension.cs
> +        /// List VMs at the given subscription.
use standard text
https://github.com/m-nash/azure-proto-sdk/blob/master/XmlDocStandard.md#listresource--listresourceasync-on-subscriptionextensions

2021-01-12 19:51 UTC, m-nash commented on azure-proto-compute/Extensions/AzureSubscriptionExtension.cs
> +        /// <param name="subscription"> The id of the Azure subscription. </param>
this isn't actually an id its the subscriptionoperation instance

2021-01-12 19:51 UTC, m-nash commented on azure-proto-compute/Extensions/AzureSubscriptionExtension.cs
> +        /// List VMs at the given subscription.
use standard text
https://github.com/m-nash/azure-proto-sdk/blob/master/XmlDocStandard.md#listresource--listresourceasync-on-subscriptionextensions

2021-01-12 19:51 UTC, m-nash commented on azure-proto-compute/Extensions/AzureSubscriptionExtension.cs
> +        /// List VMs by name at the given subscription.
use standard text
https://github.com/m-nash/azure-proto-sdk/blob/master/XmlDocStandard.md#listresourcebyname--listresourcebynameasync-on-subscriptionextensions

2021-01-12 19:51 UTC, m-nash commented on azure-proto-compute/Extensions/AzureSubscriptionExtension.cs
> +        /// List VMs by name at the given subscription.
https://github.com/m-nash/azure-proto-sdk/blob/master/XmlDocStandard.md#listresourcebyname--listresourcebynameasync-on-subscriptionextensions

2021-01-12 19:51 UTC, m-nash commented on azure-proto-compute/Extensions/AzureSubscriptionExtension.cs
> +        /// List AvailabilitySets at the given subscription.
use standard text
https://github.com/m-nash/azure-proto-sdk/blob/master/XmlDocStandard.md#listresource--listresourceasync-on-subscriptionextensions

2021-01-12 19:51 UTC, m-nash commented on azure-proto-compute/Extensions/AzureSubscriptionExtension.cs
> +        /// List AvailabilitySets at the given subscription.
use standard text
https://github.com/m-nash/azure-proto-sdk/blob/master/XmlDocStandard.md#listresource--listresourceasync-on-subscriptionextensions

2021-01-13 22:16 UTC, m-nash approved these changes

2021-01-13 22:17 UTC, merged