Workshop
m-nash/azure-proto-sdk pull request #123
Opened 2021-01-14 01:39 UTC by m-nash

2021-01-22 09:03 UTC, allenjzhang commented
>         /// <param> The <see cref="[SubscriptionOperations]" /> instance the method will execute against. </param>

There are bunch of incorrectly labelled crefs with extra []. You can do a global search/replace with these regex: cref=\"\[(.*)\]"   --> cref="$1"

---
Refers to: azure-proto-compute/Extensions/SubscriptionExtensions.cs:43 in 2419945. [](commit_id = 2419945df2b650c11899736160e069770baa4f7e, deletion_comment = False)

2021-01-26 02:51 UTC, markcowl requested changes
Some minor textual corrections - no re-review should be needed.

2021-01-26 02:51 UTC, markcowl commented on Azure.ResourceManager.Core/Adapters/PhWrappingAsyncPageable.cs
> +    /// As above, returns an AsyncPageable that transforms each page of contents  after they are retrieved from the server
```suggestion
    /// Returns an AsyncPageable that transforms each page of contents  after they are retrieved from the server
```

2021-01-26 02:51 UTC, markcowl commented on Azure.ResourceManager.Core/Adapters/PhWrappingAsyncPageable.cs
> +    /// accorgin to the profived transformation function
```suggestion
    /// according to the profived transformation function
```

2021-01-26 02:51 UTC, markcowl commented on Azure.ResourceManager.Core/ArmOperation.cs
> +    /// Abstract class for long-running or synchronous applications. If we want to add ARM-specific OM, this is where we
This should be boiler plate text from the ```Operation<T>``` definition

2021-01-27 00:26 UTC, markcowl approved these changes

2021-01-27 00:32 UTC, bquantump approved these changes

2021-01-27 00:34 UTC, merged