Add xml subnet docs
m-nash/azure-proto-sdk pull request #127
Opened 2021-01-15 17:24 UTC by bquantump

https://dev.azure.com/azure-mgmt-ex/DotNET%20Management%20SDK/_boards/board/t/DotNET%20Management%20SDK%20Team/Stories/?workitem=5053

2021-01-15 17:59 UTC, allenjzhang commented on azure-proto-network/SubnetContainer.cs
>          public async override Task<ArmOperation<Subnet>> StartCreateAsync(string name, SubnetData resourceDetails, CancellationToken cancellationToken = default)
nit:  ->  public override async

2021-01-15 18:01 UTC, allenjzhang commented
Are you missing Subnet.cs and SubnetData.cs?

2021-01-19 19:37 UTC, m-nash requested changes

2021-01-19 19:37 UTC, m-nash commented on azure-proto-network/Placeholder/SubnetData.cs
> +         /// <summary> The provisioning state of the subnet resource. </summary>
missing newline

2021-01-19 19:37 UTC, m-nash commented on azure-proto-network/Placeholder/SubnetData.cs
> +        /// <summary>An array of references to services injecting into this subnet. </summary>
missing space

2021-01-19 19:37 UTC, m-nash commented on azure-proto-network/Placeholder/SubnetData.cs
> +        /// <summary>An array of references to the external resources using subnet. </summary>
missing space

2021-01-19 19:37 UTC, m-nash commented on azure-proto-network/Placeholder/SubnetData.cs
> +        /// A read-only string identifying the intention of use for this subnet based on
should be one line

2021-01-19 19:37 UTC, m-nash commented on azure-proto-network/Placeholder/SubnetData.cs
> +        /// <summary>  Array of IP configuration profiles which reference this subnet. </summary>
missing newline

2021-01-19 19:37 UTC, m-nash commented on azure-proto-network/Placeholder/SubnetData.cs
> +        /// <summary> Nat gateway associated with this subnet. </summary>
missing newline

2021-01-19 19:37 UTC, m-nash commented on azure-proto-network/Placeholder/SubnetData.cs
> +}
missing newline at end of file

2021-01-19 19:37 UTC, m-nash commented on azure-proto-network/Subnet.cs
> +}
missing newline at end of file

2021-01-19 19:37 UTC, m-nash commented on azure-proto-network/SubnetContainer.cs
> -}
missing newline at end of file

2021-01-19 19:37 UTC, m-nash commented on azure-proto-network/SubnetOperations.cs
> +}
missing newline at end of file

2021-01-20 19:10 UTC, m-nash requested changes

2021-01-20 19:10 UTC, m-nash commented on azure-proto-network/Placeholder/SubnetData.cs
> +    /// <summary> A class representing the subnet data model. </summary>
this shouldn't be 1 line, the properties are copy paste from the existing code gen so they can be 1 line, but summary in general should be multi-line

2021-01-20 19:10 UTC, m-nash commented on azure-proto-network/Placeholder/SubnetData.cs
> +        /// <summary> Initializes a new instance of the <see cref="SubnetData"/> class. </summary>
this shouldn't be 1 line, the properties are copy paste from the existing code gen so they can be 1 line, but summary in general should be multi-line

2021-01-20 19:10 UTC, m-nash commented on azure-proto-network/Placeholder/SubnetData.cs
> +        /// <summary>An array of references to the external resources using subnet. </summary>
still missing space

2021-01-21 18:04 UTC, m-nash approved these changes

2021-01-21 18:04 UTC, merged