Common types documentation
m-nash/azure-proto-sdk pull request #128
Opened 2021-01-15 17:50 UTC by JonathanCrd

Fixed StyleCop warnings and adding the XLM documentation needed for:

- Location
- Identity
- UserAssignedIdentity
- SystemAssignedIdentity
- Sku
- ResourceIdentifier
- ResourceType
- Plan

2021-01-15 21:43 UTC, allenjzhang commented on Azure.ResourceManager.Core/Resources/ResourceIdentifier.cs
> +        /// Gets or sets the Parent. <para/>
><para/> [](start = 37, length = 7)

nit: Remove

2021-01-15 21:44 UTC, allenjzhang commented on Azure.ResourceManager.Core/Resources/ResourceIdentifier.cs
> +        /// <param name="x" >A resource id. </param>
space.

2021-01-15 21:44 UTC, allenjzhang commented on Azure.ResourceManager.Core/Resources/ResourceIdentifier.cs
> +        /// <returns>true if the resource ids are equivalent, otherwise false. </returns>
Space

2021-01-15 21:45 UTC, allenjzhang commented on Azure.ResourceManager.Core/Resources/ResourceType.cs
> +    /// TODO: Fill in comparison methods and comparison, equality, and coercion operator overloads
Remove TODO.

2021-01-15 21:46 UTC, allenjzhang commented on Azure.ResourceManager.Core/Resources/ResourceType.cs
> +        /// <param name="source"> String. </param>
String representation of a ResourceType

2021-01-15 21:46 UTC, allenjzhang commented on Azure.ResourceManager.Core/Resources/ResourceType.cs
> +        /// <param name="source">First <see cref="ResourceType"/> object. </param>
space

2021-01-15 21:47 UTC, allenjzhang commented on Azure.ResourceManager.Core/Resources/ResourceType.cs
> +        /// <param name="target"> String. </param>
>String [](start = 34, length = 6)

same as the other

2021-01-15 21:53 UTC, allenjzhang commented on Azure.ResourceManager.Core/Resources/ResourceType.cs
> +        /// <param name="source">First <see cref="ResourceType"/> object. </param>
space.  You can use this regex in find dialog to find all instances.     .*\/\/\/.*\>[^\s\.]

2021-01-16 00:52 UTC, nisha-bhatia requested changes

2021-01-16 00:52 UTC, nisha-bhatia commented on Azure.ResourceManager.Core/Resources/Identity.cs
> +        /// Gets the System Assigned Identity.
make SystemAssignedIdentity one word

2021-01-16 00:52 UTC, nisha-bhatia commented on Azure.ResourceManager.Core/Resources/Identity.cs
> +        /// <param name="user"> Dictionary with Resource Identifier key and a <see cref="UserAssignedIdentity"/> object value. </param>
add cref to ResourceIdentifier

2021-01-16 00:52 UTC, nisha-bhatia commented on Azure.ResourceManager.Core/Resources/Identity.cs
> +        /// Maintain structure of {id, (clientid, principal id)} in case of multiple UserIdentities.
Use ClientId, PrincipalId

2021-01-16 00:52 UTC, nisha-bhatia commented on Azure.ResourceManager.Core/Resources/Identity.cs
> +        /// <param name="element"> A JSON containing an identity. </param>
JsonElement, Identity

2021-01-16 00:52 UTC, nisha-bhatia commented on Azure.ResourceManager.Core/Resources/Identity.cs
> +        /// Detects if this Identity is equals to antoher Identity instance.
another

2021-01-16 00:52 UTC, nisha-bhatia commented on Azure.ResourceManager.Core/Resources/SystemAssignedIdentity.cs
> +        /// <param name="tenantId"> Application Tenant ID. </param>
Use TenantId and PrincipalId

2021-01-16 00:52 UTC, nisha-bhatia commented on Azure.ResourceManager.Core/Resources/SystemAssignedIdentity.cs
> +        /// <param name="element"> A JSON containing an identity. </param>
JsonElement

2021-01-16 00:52 UTC, nisha-bhatia commented on Azure.ResourceManager.Core/Resources/Identity.cs
> +        /// <returns> True or False depending if they are equals. </returns>
True if they are equal, otherwise False. (use the same as what it is in SystemAssignedIdentity.cs)

2021-01-16 00:52 UTC, nisha-bhatia commented on Azure.ResourceManager.Core/Resources/SystemAssignedIdentity.cs
> +        /// <returns> True if they are equals, otherwise false. </returns>
equal

2021-01-16 00:52 UTC, nisha-bhatia commented on Azure.ResourceManager.Core/Resources/UserAssignedIdentity.cs
> +        /// <param name="clientId"> Client ID. </param>
Use ClientId and PrincipalId

2021-01-16 00:52 UTC, nisha-bhatia commented on Azure.ResourceManager.Core/Resources/UserAssignedIdentity.cs
> +        /// <param name="element"> A JSON containing an identity. </param>
JsonElement

2021-01-16 00:52 UTC, nisha-bhatia commented on Azure.ResourceManager.Core/Resources/UserAssignedIdentity.cs
> +        /// <returns> True if they are equals, otherwise false. </returns>
equal

2021-01-16 01:05 UTC, YalinLi0312 requested changes

2021-01-16 01:05 UTC, YalinLi0312 commented on Azure.ResourceManager.Core/Resources/Identity.cs
> +        /// Maintain structure of {id, (clientid, principal id)} in case of multiple UserIdentities.
Maintain -> Maintains

2021-01-19 18:24 UTC, nisha-bhatia approved these changes
LGTM

2021-01-19 21:06 UTC, m-nash requested changes

2021-01-19 21:06 UTC, m-nash commented on Azure.ResourceManager.Core/Resources/Identity.cs
> +        /// Initializes a new instance of the <see cref="Identity"/> class with no <see cref="SystemAssignedIdentity"/>  or <see cref="UserAssignedIdentity"/>.
use the same text as line 29
```suggestion
        /// Initializes a new instance of the <see cref="Identity"/> class.
```

2021-01-19 21:06 UTC, m-nash commented on Azure.ResourceManager.Core/Resources/Identity.cs
> +        /// Maintains structure of {id, (ClientId, PrincipalId)} in case of multiple UserIdentities.
remove this line

2021-01-19 21:06 UTC, m-nash commented on Azure.ResourceManager.Core/Resources/Plan.cs
> +
remove extra line

2021-01-19 21:06 UTC, m-nash commented on Azure.ResourceManager.Core/Resources/Plan.cs
> +
remove extra line

2021-01-19 21:06 UTC, m-nash commented on Azure.ResourceManager.Core/Resources/ResourceIdentifier.cs
> +    /// TODO: Implement operator overloads for equality, comparison, and coercion
remove the todo line its tracked in ado now

2021-01-19 21:49 UTC, m-nash approved these changes

2021-01-19 22:59 UTC, YalinLi0312 approved these changes

2021-01-19 23:00 UTC, merged