Move Construct to Container
m-nash/azure-proto-sdk pull request #32
Opened 2020-09-22 23:21 UTC by m-nash

Fix issue with resourceIdentifier throwing on resourcegroup constructor

2020-09-23 19:05 UTC, markcowl requested changes

2020-09-23 19:05 UTC, markcowl commented on azure-proto-core/ResourceListOperations.cs
> +            if (!ArmClient.Registry.TryGetResourceType<U, T>(out type))
Per above comments, I think we need an item to remove this dependency on the registry - we could follow several patterns, like always allowing a default constructor of the resource types, or using reflection over a static ResourceType property in each class.

2020-09-23 19:05 UTC, markcowl commented on azure-proto-network/Extensions/ResourceGroupExtension.cs
> +    public static class ResourceGroupExtension
Note: I think the class name here should be plural (which the previous one also was not)

2020-09-23 19:06 UTC, markcowl commented
A few monor change suggestions - for the registry issue, it is fine to add a task or a TODO

2020-09-24 18:06 UTC, m-nash commented on azure-proto-compute/Placeholder/PhVirtualMachine.cs
> +            ArmClient.Registry.Register<VirtualMachineOperations, PhVirtualMachine>(
for now yes, it will be replaced at some point, but its still the way we get certain information

2020-10-08 22:02 UTC, markcowl approved these changes

2020-10-08 22:02 UTC, merged