Location tests
m-nash/azure-proto-sdk pull request #43
Opened 2020-10-30 18:49 UTC by JonathanCrd

2020-11-02 19:03 UTC, JonathanCrd commented
VS Code Coverage:
![image](https://user-images.githubusercontent.com/17486462/97907967-e556ba00-1cfa-11eb-8c5c-9efa57478602.png)

Cobertura analysis:
![image](https://user-images.githubusercontent.com/17486462/97908028-f6073000-1cfa-11eb-961b-cb5295de2078.png)

2020-11-09 20:49 UTC, m-nash requested changes

2020-11-09 20:49 UTC, m-nash commented on azure-proto-core-test/LocationTests.cs
> +        [SetUp]
remove if empty

2020-11-09 20:49 UTC, m-nash commented on azure-proto-core-test/LocationTests.cs
> +            Assert.IsTrue(location1.Equals("West US"));
move to a separate test since its testing Location to string comparison vs Location to Location

2020-11-09 20:49 UTC, m-nash commented on azure-proto-core-test/LocationTests.cs
> +            Assert.IsFalse(location1.Equals("WestUS"));
move to a separate test since its testing Location to string comparison vs Location to Location

2020-11-09 20:49 UTC, m-nash commented on azure-proto-core-test/LocationTests.cs
> +            Assert.AreEqual(0, location1.CompareTo("South US"));
move to a separate test since its testing Location to string comparison vs Location to Location

2020-11-09 20:49 UTC, m-nash commented on azure-proto-core-test/LocationTests.cs
> +            Assert.AreEqual(1, location1.CompareTo("East US"));
move to a separate test since its testing Location to string comparison vs Location to Location

2020-11-09 20:49 UTC, m-nash commented on azure-proto-core-test/LocationTests.cs
> +            Assert.AreEqual(-1, location1.CompareTo("West US"));
move to a separate test since its testing Location to string comparison vs Location to Location

2020-11-09 20:49 UTC, m-nash commented on azure-proto-core-test/LocationTests.cs
> +            Assert.AreEqual(1, Location.Default.CompareTo(isNull ? null : Location.Default));
add a line
Location location1 = null;
use that in the compareto instead of the trinary operator

2020-11-10 01:05 UTC, JonathanCrd commented
VS Code Coverage:
![image](https://user-images.githubusercontent.com/17486462/98614465-57a43d00-22ad-11eb-8571-1f05f9553a3a.png)

Cobertura analysis:
![image](https://user-images.githubusercontent.com/17486462/98614646-b8cc1080-22ad-11eb-9895-18cd411e9dfb.png)

2020-11-10 01:21 UTC, m-nash requested changes

2020-11-10 01:21 UTC, m-nash commented on azure-proto-core/Resources/Location.cs
> +            return string.Compare(this.Name, other.Name);
```suggestion
            return Name.CompareTo(other.Name);
```

2020-11-10 01:21 UTC, m-nash commented on azure-proto-core/Resources/Location.cs
> +            return string.Compare(this.Name, other);
```suggestion
            return Name.CompareTo(other);
```

2020-11-10 01:21 UTC, m-nash commented on azure-proto-core-test/LocationTests.cs
> +
Remove extra line here

2020-11-10 01:41 UTC, m-nash approved these changes

2020-11-10 01:48 UTC, merged