Unit test for ListAtContext
m-nash/azure-proto-sdk pull request #66
Opened 2020-12-10 20:52 UTC by bquantump

2020-12-10 23:35 UTC, m-nash requested changes

2020-12-10 23:35 UTC, m-nash commented on ClientTests/ResourceListOperationsTest.cs
> +        private static void TestListActivator<T, U>()
Can we give the type parameters semantic names like TOperations etc?

2020-12-10 23:35 UTC, m-nash commented on ClientTests/ResourceListOperationsTest.cs
> +            function.DynamicInvoke(new object [] {resource});
Can we trap the return type here which I believe should be a T and assert some of its properties.  Like it should have the same context and resource property values that we set on lines 23 and 25-27?

2020-12-10 23:35 UTC, m-nash commented on azure-proto-compute/Placeholder/AvailabilitySetData.cs
> +
I think you can revert this file

2020-12-10 23:35 UTC, m-nash commented on azure-proto-core/ResourceListOperations.cs
> +        where TOperations : ResourceOperationsBase<TOperations, TResource>
where clauses should be indented similar to the other methods

2020-12-14 20:01 UTC, markcowl requested changes
I think this is fine, modulo the spelling change, and I don't want to spend too much time on this, as we won't need this once we move to the .Net repo, but I wonder if this wouldn't be simpler if we simply had a constructor inthe concrete Operatiosn classes that took the model type from the generated code as a parameter

2020-12-14 21:48 UTC, m-nash approved these changes

2020-12-14 22:32 UTC, merged