WIP: Client options merge with client context #4939
m-nash/azure-proto-sdk pull request #82
Opened 2020-12-17 22:06 UTC by bquantump

2020-12-17 22:24 UTC, m-nash requested changes

2020-12-17 22:24 UTC, m-nash commented on Azure.ResourceManager.Core/ArmResourceOperations.cs
> +        public ArmResourceOperations(AzureResourceManagerClientContext context, ResourceIdentifier id)
Should have specified in the ADO item but we should follow the standard naming convention of [ClientName]Options instead of [ClientName]Context

2020-12-18 21:14 UTC, m-nash submitted a review, later dismissed

2020-12-18 21:14 UTC, m-nash commented on Azure.ResourceManager.Core/AzureResourceManagerClientOptions.cs
> +        public AzureResourceManagerClientOptions(AzureResourceManagerClientOptions other)
Why do we need this constructor?

2020-12-18 21:14 UTC, m-nash commented on Azure.ResourceManager.Core/AzureResourceManagerClientOptions.cs
> +        private void copy(AzureResourceManagerClientOptions other)
method names should have capitals

2020-12-18 21:14 UTC, m-nash commented on Azure.ResourceManager.Core/ResourceGroupContainer.cs
>  }
missing newline

2020-12-18 21:14 UTC, m-nash commented on Azure.ResourceManager.Core/ResourceListOperations.cs
> +            AzureResourceManagerClientOptions clientContext,
rename variable to clientOptions

2020-12-18 21:14 UTC, m-nash commented on Azure.ResourceManager.Core/ResourceListOperations.cs
> +            AzureResourceManagerClientOptions clientContext,
rename variable to clientOptions

2020-12-18 21:14 UTC, m-nash commented on Azure.ResourceManager.Core/ResourceListOperations.cs
> +            AzureResourceManagerClientOptions clientContext,
rename variable to clientOptions

2020-12-18 21:14 UTC, m-nash commented on Azure.ResourceManager.Core/ResourceListOperations.cs
> +            AzureResourceManagerClientOptions clientContext,
rename variable to clientOptions

2020-12-18 21:14 UTC, m-nash commented on Azure.ResourceManager.Core/ResourceListOperations.cs
> +            AzureResourceManagerClientOptions clientContext)
rename variable to clientOptions

2020-12-18 21:14 UTC, m-nash commented on Azure.ResourceManager.Core/ResourceListOperations.cs
> +            AzureResourceManagerClientOptions clientContext)
rename variable to clientOptions

2020-12-18 21:14 UTC, m-nash commented on Azure.ResourceManager.Core/ResourceListOperations.cs
> +        private static Func<GenericResourceExpanded, TOperations> CreateResourceConverter<TOperations, TResource>(AzureResourceManagerClientOptions clientContext)
rename variable to clientOptions

2020-12-18 21:14 UTC, m-nash commented on azure-proto-network/NetworkSecurityGroupOperations.cs
> +        internal NetworkSecurityGroupOperations(AzureResourceManagerClientOptions parent, ResourceIdentifier context)
rename parent to options and context to id

2020-12-18 21:14 UTC, m-nash commented on azure-proto-network/NetworkSecurityGroupOperations.cs
> +        public NetworkSecurityGroupOperations(AzureResourceManagerClientOptions parent, TrackedResource context)
rename parent to options and context to resource

2020-12-18 21:35 UTC, bquantump commented on Azure.ResourceManager.Core/AzureResourceManagerClientOptions.cs
> +        public AzureResourceManagerClientOptions(AzureResourceManagerClientOptions other)
Not needed, loosing my mind apparently

2020-12-22 00:56 UTC, nisha-bhatia commented on Azure.ResourceManager.Core/AzureResourceManagerClientOptions.cs
>  }
Add newline at end of this file

2020-12-22 02:05 UTC, JonathanCrd reviewed
I pointed some places in which the XML documentation does not match the parameters of the constructor.

2020-12-22 02:05 UTC, JonathanCrd commented on azure-proto-authorization/RoleAssignmentOperations.cs
> +        internal RoleAssignmentOperations(AzureResourceManagerClientOptions options, Resource resource)
XML Documentation does not match the constructor params.

2020-12-22 02:05 UTC, JonathanCrd commented on azure-proto-authorization/RoleAssignmentOperations.cs
> +        /// <param name="options,">The resource manager options, to use with these operations.</param>
XML Documentation does not match the constructor params.

2020-12-22 20:13 UTC, JonathanCrd approved these changes
Looks good to me

2020-12-22 20:13 UTC, JonathanCrd approved these changes

2020-12-22 20:26 UTC, nisha-bhatia approved these changes
Looks good to me!

2020-12-22 20:27 UTC, merged